name: build-docker-image-and-push-to-hub

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: caian/yatt

    steps:
      - name: Checkout to yatt
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "caian"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          export GIT_TAG="$(git tag | tail -n 1)"
          export IMAGE_LATEST="$IMAGE_NAME:latest"
          export IMAGE_TAGGED="$IMAGE_NAME:$GIT_TAG"
          docker build -t "$IMAGE_LATEST" .
          docker push "$IMAGE_LATEST"
          docker tag "$IMAGE_LATEST" "$IMAGE_TAGGED"
          docker push "$IMAGE_TAGGED"
