name: code-check

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to yatt
        uses: actions/checkout@v2

      - name: Set up NodeJS 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm i

      - name: Perform all checkings
        run: npm run check:all
