name: perform-code-checkings

on:
  push:
    branches: '*'
    tags: '*'
    paths-ignore: '**.md'

  pull_request:
    branches: '*'
    tags: '*'
    paths-ignore: '**.md'

jobs:
  code-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs-version: ['17.x', '16.x', '14.x', '12.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.x

      - name: Setup NodeJS ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs-version }}
          cache: pnpm

      - name: Cache pnpm store
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ~/.pnpm-store
          key: ${{ env.preffix }}-cache-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ env.preffix }}-cache-${{ env.cache-name }}-
            ${{ env.preffix }}-cache-
            ${{ env.preffix }}-
        env:
          cache-name: code-check
          preffix: ${{ runner.os }}-node-${{ matrix.nodejs-version }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i

      - name: Perform all checkings
        run: pnpm run all
