name: perform-code-checkings

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  code-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs-version: ['17', '16.13', '14.18', '12.22']

    steps:
      - name: Checkout to yatt
        uses: actions/checkout@v2

      - name: Set up NodeJS ${{ matrix.nodejs-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodejs-version }}

      - name: Install dependencies
        run: npm i

      - name: Perform all checkings
        run: npm run all
